### PR TITLE
[Node20] Upgrade CI and dependencies to work with Node v20

### PR DESCRIPTION
**Pull request by kofi-q**
## Overview

https://github.com/votingworks/vxsuite/issues/4163

Upgrading VxSuite to build/run on Node v20.16.0:
- Force lock the `nan` package to `v.2.20.0` for all peer dependencies to make sure they use a Node20-compatible version
- Bump `pnpm` version to `8.15.5`, which seems to be the earliest `^8` version that plays nice with Node20. Will consider bumping `pnpm` to v9 later on.
- Bump version string in `.node-version`
- Sneaking in a couple minor updates to enable building with rust 1.81.0
-  Use `v4.1.0` of the CI docker image (created in https://github.com/votingworks/vxsuite-build-system/pull/133), which has:
  -  node@20.16.0
  - pnpm@8.15.5
  - rust@1.81.0

## Demo Video or Screenshot
https://app.circleci.com/pipelines/github/votingworks/vxsuite/17050

## Testing Plan
- Ran tests and apps locally - specifically tested USB and smartcard reader interactions, printing, and QR code detection/interpretation.

## Checklist

- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.~

- ~[ ] I have added a screenshot and/or video to this PR to demo the change~
- ~[ ] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates~

### CODE REVIEW

**Comment by kofi-q** [comment]
I think some of the additional files automatically pulled y'all in, but feel free to ignore

**Comment by kofi-q** [comment]
Also, a little concerned about the flaky [node-gyp build step](https://app.circleci.com/pipelines/github/votingworks/vxsuite/17066), so going to look into that a bit to see what's causing the occasional failures

**Comment by kofi-q** [comment]
Ok, sorry for the commit thrash - wanted to make sure the pnpm install's stable now. Seems like there's an issue with running concurrent node-gyp builds (at least with pnpm 8.x, saw some signals that it might be fixed in 9.x).

Disabled concurrency for now, which will probably slow down CI installs a bit when npm deps change, but will look into a pnpm 9 upgrade later as a followup.

**Review by eventualbuddha — APPROVED** [review]
Did some basic spot-checking of this in dev–all looks good! Thanks, @kofi-q! 🎉

**Pull request merged**
