### PR TITLE
Consolidate Signature Page and Polls Tally Report

### PR DESCRIPTION
**Pull request by adghayes**
## Overview
Completes most of #1836, but does not add the VxQR code to the single-page report. Consolidates our polls report header page (with signature space) and the tally report. 

### New Report Look

[conslidated-report-rev1.pdf](https://github.com/votingworks/vxsuite/files/9690826/conslidated-report-rev1.pdf)

### Old Report For Reference

[unconsolidated-report-main.pdf](https://github.com/votingworks/vxsuite/files/9690827/unconsolidated-report-main.pdf)

## Testing Plan
- Manual Testing
- Updated RTL Tests

## Checklist
- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.
- [ ] I have added JSDoc comments to any newly introduced exports

- [x] I have added a screenshot and/or video to this PR to demo the change
- [x] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

**Comment by adghayes** [comment]
@mattroe we discussed putting the signatures at the bottom of each page but... I didn't realize that wasn't so simple. For each report (not each page), we can easily put the signature section above or below the tally results. I think top is better because on the bottom there's a possibility that the signature section ends up orphaned on the next page. 

It makes the language a little weird, "the undersigned" is no longer under anything. I'm not sure if that language is in state law, or just copying Accuvote. 

Now looking just for layout feedback.

**Comment by adghayes** [comment]
To whoever reviews - I did a little change before the report consolidation that is actually more closely related to #2617. Because we can now print additional reports, the time printed might diverge from the time polls were closed. So I made sure we can specify both separately (and include both in the new report). I also renamed or separated cases of `timeSaved` to `timePollsToggled` because that is what matters and is more relevant on the report IMO.

**Review by benadida — APPROVED** [review]
suggest squashing snapshot and test updates into main commit so we don't have a broken commit in the main branch.

**Comment by adghayes** [comment]
@benadida, sounds good. Currently, "Squash and merge" is the only merge option we have into main. "Rebase and merge" is technically an option but doesn't work with commit signing.

**Comment by benadida** [comment]
> @benadida, sounds good. Currently, "Squash and merge" is the only merge option we have into main. "Rebase and merge" is technically an option but doesn't work with commit signing.

Does squash and merge even work? I think you have to squash them on your machine first.

**Comment by adghayes** [comment]
cc @mattroe, to peek the reports

**Comment by mattroe** [comment]
Just printed out to review a physical copy. My thoughts:
- The smallest font size on this page is quite hard to read in print. This applies to the timestamp, cert signature text, section, and cast/overvote/undervote. I think we should increase this a bit.
- The scanner ID could use it's own line in larger font. It gets lost in this.
- Signature area should have a little bit more padding. A small signature easily goes over the other text area.

**Comment by adghayes** [comment]
@mattroe, I don't really want to revamp the pre-existing formatting of the report, but agree the signature area could use more clarity. Here's my suggestion:

**Change**:
- Cert Signature Text --> Larger Font
- Signature Space --> More Padding

**Don't Change**:
- Other small fonts

Question - what is the user story where the Scanner ID is important to whoever is reading the report, in which case it will be important to be more prominent? I made it small because I think it won't matter in most cases when reading this report.

**Comment by adghayes** [comment]
I am interested in keeping the report compact to avoid multi-page reports as much as possible.

**Comment by mattroe** [comment]
To be clear, this first version meets the core requirements for NH. Feel free to just take a quick pass at the certification signature section and move on. I have some additional thoughts on that below.

Re: font size, we can also just follow-up on overall design improvements for the report later. I was simply recognizing how small some of the fonts are on this page when reviewing the new content.

Re: scanner ID, thanks for pushing, you're most likely correct that this field will not be used often other than when multiple tabulators are used in a given precinct. My thought was that it would not surrender too much vertical real estate to move from the timestamp line.

Re: certification copy adjustment, you may want to see what it looks like to style "Certification Signatures" in bold and the sentence in normal text like you did for the scanner ID. I recognize the copy was in bold on the original report style, but I think we should keep the key (bold): value (unstyled) font design consistent in the report header.

**Comment by adghayes** [comment]
@mattroe does the signature section on this look a little better? If so, will merge and move on.

[that-new-new-report.pdf](https://github.com/votingworks/vxsuite/files/9701377/that-new-new-report.pdf)

**Comment by mattroe** [comment]
Yep, move on!

**Pull request merged**
