### PR TITLE
feat(ps): guide poll workers after open/close polls

### PR DESCRIPTION
**Pull request by beausmith**
This screen share shows the flow: open polls, scan a ballot, close polls, export results to usb…
https://user-images.githubusercontent.com/28444/150447871-f6d0ad0f-805e-45c7-995e-92fbdeddf43c.mov

### CODE REVIEW

**Comment by beausmith** [comment]
I'll get to the tests soon! But please review for general idea.

**Comment by mattroe** [comment]
Most important change IMO is prompting pollworkers with a green button to export usb immediately after closing. 

One aspect that isn't obvious from testing the current flow with election commissioners yesterday is that there is no indication you need to take the pollworker card to VxMark to actually print the reports. I don't think we should treat this as self-evident and feel like an explicit cue to VxMark after opening/closing would be valuable.

**Comment by ginvdr** [comment]
Comments:
1. Open Polls Screen - turn Open Polls for All Precincts button green
2. Polls Close Screen - turn Close Polls for All Precincts button green
3. On USB Drive Screen - turn Export button green (do this in both places)
4. Polls are Closed Screen - after they export the CVRs, turn the Export Results to USB Drive button gray?  Or some other indicator that they've completed it

CVR export seems much easier now. Agree with Roe that a prompt to remove the card and take to VxMark is probably helpful.

**Comment by benadida** [comment]
@beausmith important to point out that the flow you're showing is when the printer is connected. In the setups @ginvdr and @mattroe are thinking about (Ms), there's no printer connected to VxScan, we're writing data to the card for VxMark printing. So worth seeing how that flow goes and in particular how we prompt sending.

Otherwise, I like these changes and agree with Ginny's comments.

**Comment by beausmith** [comment]
Thx. For all this feedback. Will incorporate and post another video today.

**Review by eventualbuddha — APPROVED** [review]
Approving for code style etc. Others can take the business logic as it's already being discussed in this PR.

**Comment by eventualbuddha** [comment]
[The warning in the precinct-scanner tests](https://app.circleci.com/pipelines/github/votingworks/vxsuite/2939/workflows/a1626685-9dce-47bb-87cf-a7b97bf67e3a/jobs/47565?invite=true#step-108-35) should be fixed by #1390.

**Comment by beausmith** [comment]
Merged #1390 to main. Rebased and waiting on tests.

**Pull request merged**
