### PR TITLE
refactor(types): shrink `Result`

### PR DESCRIPTION
**Pull request by eventualbuddha**
Per discussions with @votingworks/eng, I'm trying out a more minimal `Result` type.

### CODE REVIEW

**Review by jonahkagan — APPROVED** [review]
looks like a good simplified approach. the only suggestion i have is to maybe rename `unwrap` to something that makes it clear it's not safe

**Comment by eventualbuddha** [comment]
> looks like a good simplified approach. the only suggestion i have is to maybe rename `unwrap` to something that makes it clear it's not safe

I like that. I'll do `unsafeUnwrap`.

**Comment by eventualbuddha** [comment]
Thanks for the 👍 @jonahkagan.

I'm looking for one more 👍 from @beausmith, @carolinemodic, or @benadida before merging since you all have to live with this 😉

**Review by carolinemodic — APPROVED** [review]
I like this.

**Pull request merged**
