### PR TITLE
Alphabetize precincts when printing full tally report

### PR DESCRIPTION
**Pull request by carolinemodic**
Alphabetizes the precinct list when printing all precincts for the test deck. It didn't seem like there were any tests related to this screen yet to be able to add a test for this, but tested manually. And definitely lmk if I'm missing something. 

https://github.com/votingworks/vxmail/issues/317

### CODE REVIEW

**Review by eventualbuddha — COMMENTED** [review]
Two things:
1. Do we actually want this? @benadida 
2. Can we add a test?

**Comment by benadida** [comment]
> 1. Do we actually want this? @benadida

Yeah, we do, if there's a print failure, Matt Roe mentioned alphabetizing would be a lot better so you know where things stopped.

**Comment by carolinemodic** [comment]
Ok this was likely overkill for this PR but added a test, since there isn't a lot of tests in election-manager yet I had to set some things up, so renderInAppContext is modelled after testUtils in the bmd repo (which some slight differences as I was getting typescript / eslint errors)

**Review by eventualbuddha — APPROVED** [review]
Thanks! Hopefully that'll make the next test that much easier.

**Pull request merged**
