### PR TITLE
feat(ps+ui): More screen design progress.

### PR DESCRIPTION
**Pull request by beausmith**
The following screens are not finished. Still much to do, including:
- increase overall font size for voter screens
- admin screen
- poll worker screen
- create icons for main voter screens
- test drive and tweak until perfect!

image

image

image

image

image

image

### CODE REVIEW

**Review by carolinemodic — APPROVED** [review]
The dismiss and tabulate anyways buttons seem a little hard to find? Maybe on the screen size of a tablet its easier to notice though.

**Comment by benadida** [comment]
Looking only at look-and-feel: shouldn't the text be *way* bigger?

**Comment by beausmith** [comment]
@carolinemodic - Yes, size and position of buttons still not quite right. 

@ben - See first bullet point: "increase overall font size for voter screens"

**Comment by beausmith** [comment]
@carolinemodic - Yes, size and position of buttons still not quite right. 

@benadida - See first bullet point: "increase overall font size for voter screens"

**Comment by benadida** [comment]
> @benadida - See first bullet point: "increase overall font size for voter screens"

lol, you're saying I should *read* the description? Ok, ok, you're right :)

**Pull request merged**
