### PR TITLE
refactor(fixtures): use `ElectionDefinition` for everything

### PR DESCRIPTION
**Pull request by eventualbuddha**
Reformats all JSON fixtures to use 4-space indents and a trailing newline so that TypeScript will not change them when copying into the `outDir` for each project. Reformatting changes the election hash, which invalidates the definition for most purposes.

### CODE REVIEW

**Comment by benadida** [comment]
@eventualbuddha I'm a little thrown off by the idea of having concatenated strings as the official sample definition files. Is there no way to just have JSON files in a particular directory that TS won't reformat? Maybe if they're `.json.txt` or something that forces TS to ignore them?

**Comment by eventualbuddha** [comment]
> @eventualbuddha I'm a little thrown off by the idea of having concatenated strings as the official sample definition files. Is there no way to just have JSON files in a particular directory that TS won't reformat? Maybe if they're `.json.txt` or something that forces TS to ignore them?

Updated to simply format the JSON files the way TS would format them so that the "reformat" is a no-op.

**Comment by eventualbuddha** [comment]
Also filed https://github.com/microsoft/TypeScript/issues/43436 for the TS team's consideration.

**Comment by eventualbuddha** [comment]
Can't use `fs.readFileSync` in `@votingworks/fixtures`:

image

BMD fails to load ☹️

**Comment by eventualbuddha** [comment]
@benadida talk me off the ledge: https://github.com/jirutka/ts-transformer-inline-file

**Comment by benadida** [comment]
> @benadida talk me off the ledge: https://github.com/jirutka/ts-transformer-inline-file

Would that work at preserving the exact text of the files?

I don't have a strong feeling against gnarly build tools, we already use them, I just want to make sure that there's a single source of truth that ideally is just a JSON file.

**Comment by eventualbuddha** [comment]
> Would that work at preserving the exact text of the files?

I believe so. Reviewing the code, I found this is how they actually do it: https://github.com/jirutka/ts-transformer-inline-file/blob/e75c2690b2383d2bfd01afd97cde863440696f7b/transformer.ts#L91-L95

So it's reading the file as utf-8 and then using a (presumably well-tested) TS compiler API to build a string literal.

> I don't have a strong feeling against gnarly build tools, we already use them, I just want to make sure that there's a single source of truth that ideally is just a JSON file.

I'll think about it.

**Pull request closed without merging**
