### PR TITLE
feat(em): automate building ballot packages

### PR DESCRIPTION
**Pull request by eventualbuddha**
Adds the `script/build-ballot-package` script for creating ballot packages from election definitions quickly via the command line. It uses puppeteer to orchestrate Chrome and provides just enough of the features from kiosk-browser to support this use case.

https://asciinema.org/a/UYRpdjnaWPWWhPKTlcbmuOSXV

### CODE REVIEW

**Review by benadida — APPROVED** [review]
have you checked that this generates a byte-for-byte identical ballot package? I want to make sure we're printing the same way.

**Comment by eventualbuddha** [comment]
> have you checked that this generates a byte-for-byte identical ballot package? I want to make sure we're printing the same way.

This is a reasonable concern, but I'm not really sure how to check this other than simply viewing the PDFs manually. Maybe there's a way to use PDF.js to figure out what all the drawing commands are and compare them? As is, the Election Manager web UI in kiosk-browser doesn't produce byte-for-byte the same values every time. Part of this is timestamps, but I think there's more to it than that.

**Comment by eventualbuddha** [comment]
Well, I'll be damned. [`diff-pdf`](https://vslavik.github.io/diff-pdf/) shows there are visible differences:

diff-p1

I am not sure why, though it's a near certainty that electron and puppeteer are not using the same version of Chrome. I guess I need some way to script kiosk-browser.

**Comment by benadida** [comment]
I wouldn't completely give up, i think we actually need to understand why it's rendering differently here. Maybe @beausmith can help?

**Pull request closed without merging**
