### PR TITLE
Build BMD with ballot-encoder

### PR DESCRIPTION
**Pull request by eventualbuddha**
This shouldn't really change the effective workflow at all, but under the hood it makes some changes:

* `yarn start` or `yarn test` etc in BMD now use a wrapper `react-scripts` that ensures the dependencies are built before running the underlying command, and get re-built as changes are made. This means a few seconds delay at startup but otherwise should function as before.
* ballot-encoder now has two TypeScript configs so that the `tsc --build` call from `bmd` does not try-and fail-to build the tests.
* node_modules are now mostly at the root for these projects. Various packages had to be added to the `nohoist` or `resolutions` config in the root `package.json` in order to make TypeScript happy.

### CODE REVIEW

**Review by carolinemodic — APPROVED** [review]
This is exciting!! Glad we're making progress towards a real monorepo world. This lgtm but I do wonder if this might cause merging issues with @beausmith 's approot refactor.

**Comment by eventualbuddha** [comment]
@carolinemodic that’s a reasonable question. @beausmith, your changes were primarily in `AppRoot`, right? Hopefully that’d be pretty orthogonal to this change.

Did anyone actually get to try this out? Does it work as expected?

**Comment by carolinemodic** [comment]
@eventualbuddha I pulled locally, ran yarn install from the root and was able to run bmd fine but then I tried to run election-manager and got the error below: 
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-jest": "^26.6.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-jest was detected higher up in the tree:

  /home/caroline/code/vxsuite/node_modules/babel-jest (version: 24.9.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-jest" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /home/caroline/code/vxsuite/node_modules/babel-jest is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-jest in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-jest.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

error Command failed with exit code 1.
```

**Comment by eventualbuddha** [comment]
@carolinemodic thanks, I hadn't tried that recently. Should work now.

**Comment by carolinemodic** [comment]
cool, works now!

**Comment by eventualbuddha** [comment]
Alright, I'm going to merge this as-is and I'll help out with any issues that arise.

**Pull request merged**
