### PR TITLE
fix(election-manager): encode election data properly when writing admin card

### PR DESCRIPTION
**Pull request by jonahkagan**
## Overview
Task: #1931

When encoding admin cards, the browser seems to convert LF to CRLF line endings when making a multi-part form request. This causes election hash mismatches. To prevent this, we use x-www-url-encoded encoding in the POST submission.

## Demo Video or Screenshot
N/A

## Testing Plan 
Manually tested

## Checklist
- [ ] ~~I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.~~
- [ ] ~~I have added JSDoc comments to any newly introduced exports~~

### CODE REVIEW

**Comment by eventualbuddha** [comment]
A possible alternate solution:

```diff
diff --git a/frontends/election-manager/src/screens/smartcards_screen.tsx b/frontends/election-manager/src/screens/smartcards_screen.tsx
index 2d2505be0..0e09a6758 100644
--- a/frontends/election-manager/src/screens/smartcards_screen.tsx
+++ b/frontends/election-manager/src/screens/smartcards_screen.tsx
@@ -141,7 +141,10 @@ export function SmartcardsScreen(): JSX.Element {
       p: passcode,
     });
     formData.append('short_value', shortValue);
-    formData.append('long_value', electionData);
+    formData.append(
+      'long_value',
+      new Blob([electionData], { type: 'application/octet-stream' })
+    );
     const response = await fetch('/card/write_short_and_long', {
       method: 'post',
       body: formData,
```

**Comment by benadida** [comment]
Before we push forward, I'm wary of ... what caused this regression? Are we actually writing the wrong data to the card?

Could this be... a kiosk-browser / electron / chromium behavior change?

**Comment by benadida** [comment]
I'm still confused as to what caused this regression. In any case, I agree with @jonahkagan's diagnosis, and have a bit more data as to what's going on: `FormData` uses `multipart/form-data` as an encoding type, and that just sends the raw text, but somewhere in the HTTP pipeline, new lines are rewritten. If a different encoding type were used, specifically ,`x-www-form-url-encoded`, then this shouldn't happen. I imagine this behavior changed, probably to be more up to HTTP spec, with our Electron upgrade, but I'm not sure.

I'm a little wary of @jonahkagan's proposed solution, because if later the card data legitimately includes `\r\n` then we will be in trouble.

I think @eventualbuddha's approach of changing the way the form is submitted so that the content bytes are truly respected is the better path. I don't know for sure if that code works, @eventualbuddha, but assuming it does at preserving the exact bytes, let's do that.

**Comment by benadida** [comment]
taking over this PR as per discussion in standup today. Using @eventualbuddha's solution and testing it.

**Comment by benadida** [comment]
Turns out @eventualbuddha's solution doesn't make flask happy... not sure if we'd have to parse the form differently.

Instead, I am manually putting together a url-encoded POST body.

**Review by eventualbuddha — APPROVED** [review]
I'm guessing the octet-stream thing didn't work?

**Comment by benadida** [comment]
> I'm guessing the octet-stream thing didn't work?

Not without modifying the server side, which felt a lot riskier.

**Pull request merged**
