### PR TITLE
Desktop SearchSelect

### PR DESCRIPTION
**Pull request by jonahkagan**
## Overview

Updates the SearchSelect component to work with the desktop theme. Also adds a disabled state, since we'll need that in forms in VxDesign.

## Demo Video or Screenshot
Single

https://github.com/votingworks/vxsuite/assets/530106/c1fe2701-3abb-4008-871f-0c18d761d87b

Multi

https://github.com/votingworks/vxsuite/assets/530106/06a7196b-4159-4905-b2ec-d9299d16ef77

## Testing Plan
Only styling changed, so existing tests mostly work. Added a few unit tests for disabled state and desktop theme for coverage.

## Checklist

- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.

- [ ] I have added a screenshot and/or video to this PR to demo the change
- [ ] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

**Review by adghayes — COMMENTED** [review]
The only consumers for these dropdowns are the report builder(s) in VxAdmin. With the styles optimized for touch, they get a little funky: 

Screen Shot 2023-11-02 at 12 30 00 PM

I'm not sure if you'll get to the VxAdmin revamp before we cut a release for NH. A few options I can think of:
- Let it look a little funky, if you'll for sure get to VxAdmin before release
- It doesn't look too bad, some icons and words just need to be centered. Make some styling changes in the filter and group editor components
- Wrap those components in the desktop theme so they look like they will eventually

**Comment by jonahkagan** [comment]
Great catch, I'll see if it's easy to fix on the VxAdmin side

**Comment by adghayes** [comment]
I think it will be, just adjusting some of my ad hoc styling on the editor components.

**Comment by jonahkagan** [comment]
Ok, I was able to clean this up with a mix of adjustments to the filter editor components as well as the SearchSelect component.

Screenshot 2023-11-02 at 2 55 25 PM
Screenshot 2023-11-02 at 2 55 32 PM
Screenshot 2023-11-02 at 2 55 41 PM

**Review by adghayes — APPROVED** [review]
Thanks for digging in the VxAdmin styling!

**Pull request merged**
