### PR TITLE
feat(EM): Support ballot density.

### PR DESCRIPTION
**Pull request by beausmith**
See ballot examples in Slack.

### CODE REVIEW

**Comment by beausmith** [comment]
@eventualbuddha - Halp? I'm unsure what to do about the module-scan test failures.

**Comment by eventualbuddha** [comment]
> @eventualbuddha - Halp? I'm unsure what to do about the module-scan test failures.

It's gotten more flaky. I think we're going to have to disable that test in CI.

**Review by benadida — APPROVED** [review]
This is a beautiful, minimal change with maximal impact. Love it.

**Comment by benadida** [comment]
I'm going to merge this so I can test with as many changes merged as possible.

**Pull request merged**
