### PR TITLE
fix(hmpb-interpreter): be more resiliant to stray marks

### PR DESCRIPTION
**Pull request by eventualbuddha**
Stray marks can be phantoms created by folds, or actual pen marks. This changes the filter of what is considered a plausible contest box by looking not at the bounding box size but the size determined by the median of the four edges.

These examples below (used as fixtures in the tests) show how the bounding box would be considered too wide to be a real contest box.

| Before | After |
| --- | --- |
| 20201102_202458-ballot-0071-eaf48295-f2e6-48b9-a542-10619587a8bc-original-rotated-layout | layout-fixed |
| stray-mark-broken | stray-mark-fixed |

### CODE REVIEW

**Review by carolinemodic — COMMENTED** [review]
So I’m guessing the idea here is that in a case with 1 horizontal fold there will be 3 edges, 2 from the actual contest box and 1 (much larger one) from the fold and by taking the median we ignore that fold one? Is there a reason to not just reject any edges that surpass the max expected width instead of only checking that at the very end? 

Also curious how extensive our testing is here, I see you added those examples to the tests, are the existing tests just a couple of random examples or is it possible to run this on like the full dataset from Choctaw to make sure we aren't regressing on any ballots we can identify today?

**Comment by eventualbuddha** [comment]
> So I’m guessing the idea here is that in a case with 1 horizontal fold there will be 3 edges, 2 from the actual contest box and 1 (much larger one) from the fold and by taking the median we ignore that fold one?

The names are perhaps a bit misleading. An "edge" here doesn't necessarily refer to a discovered line in the image. `findShape` looks starting at a black pixel and then checks all adjacent points that it hasn't already visited to see if they are also black pixels. If they are, it continues looking from _those_ points too until it's found all contiguous black pixels. It tracks the min/max x & y values of the pixels it finds, which become the `bounds` of the returned `Shape`. It also tracks the edges, where an "edge" is the outermost black pixels inside the bounds in the directions we care about: up/down/left/right. So the _left edge_ is the points whose `x` value comes from the leftmost (minimum) black pixel contained in the shape for each `y` value in the shape's `bounds`. The _top edge_ is, similarly, the points whose `y` value comes from the topmost (minimum) black pixel contained in the shape for each `x` value in the shape's `bounds`. Etc.

Thus, there is no "edge" for the black part from a fold. You simply have an edge that has a discontinuity in it, i.e. a pretty steady series of points like the right edge in the example image (values made up):

```
(x=2000, y=2000) # edge is pretty straight up and down
(x=2000, y=2001)
(x=2000, y=2002)
(x=2000, y=2003)
(x=2000, y=2004)
(x=2000, y=2005)
(x=2000, y=2006)
(x=2000, y=2007)
(x=2050, y=2008) # start of discontinuity
(x=2049, y=2009)
(x=2048, y=2010)
(x=2047, y=2011)
(x=2046, y=2012) # edge works diagonally down-left
```

Looking at the median of this would yield a right edge median of ~2000, effectively ignoring the discontinuity for "sizing" purposes.

> are the existing tests just a couple of random examples?

It's more than a couple, but it is a relatively small set compared to number of sheets we see in a real election.

> is it possible to run this on like the full dataset from Choctaw to make sure we aren't regressing on any ballots we can identify today?

It'd be great to be able to run CI on a larger set of ballots from e.g. Choctaw. We'd need to figure out where to put them such that our CI instances can read them but they're not otherwise public. Something to add to our todo list.

**Comment by eventualbuddha** [comment]
Running against the absentee scans from Marshall County from 2020-11-03, it fixes 139/5407 that were previously uninterpreted. However, it also breaks 56 that previously did scan fine. Here's an example of one that read fine before but doesn't with this change. It has a particularly choppy contest box edge on the left:

image

All those gaps on the left edge brings its median way over to the right, resulting in an effective width of 4px. Thus, it gets skipped and the page is uninterpreted. I think I can't use this method exclusively because of this problem.

**Comment by benadida** [comment]
@eventualbuddha reading your last comment... are you still looking to merge this or is this back to a WIP?

**Comment by eventualbuddha** [comment]
> @eventualbuddha reading your last comment... are you still looking to merge this or is this back to a WIP?

Making this a draft.

**Review by benadida — COMMENTED** [review]
I'll await resubmission :)

**Pull request closed without merging**
