### PR TITLE
Remove "Other" External Tallies

### PR DESCRIPTION
**Pull request by adghayes**
_review note: read below. you may want to trust the linter for these changes, especially the last two commits. otherwise review by commit_

## Overview

Previously we had a concept of "External Tallies" - tallies imported from another tabulation system. We then introduced manual data, and treated it as a type of "External Tally." Recently, we stopped supporting (and do not plan to support) any type of "External Tally" other than manually entered data. 

This PR (95% a refactor) encodes that change, not anticipating _plural_ "Externally Tallies" anymore (commits 1 - 16) and renaming "External" to "Manual" (commits 17 - 19). There are a few copy changes, the 5% of this PR which is not a refactor. See pictures below:

## Demo Video or Screenshot

Previously said "External Results (Manually Added Data)" instead of "Manually Added Results":
manually-added-results-tally-screen

Previously said "External Results (Manually Added Data)" instead of "Manually Added Results":
manually-added-results-reports-screen

Previously said "Have all CVR and external results files been loaded? Once results are marked as official, no additional CVR or external files can be loaded." instead of "Have all CVR files been loaded? Once results are marked as official, no additional CVR files can be loaded."
mark-official

## Testing Plan
- automated testing refactored
- manual pass

## Checklist

- [x] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.

- [x] I have added a screenshot and/or video to this PR to demo the change
- [x] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

**Comment by adghayes** [comment]
@carolinemodic @kofi-q now that I see the screenshots here I think maybe I should change the column row labels "Manually Added Results" to "Manually Entered Results" to match the heading on the tally screen. I also think "Entered" is a little more accurate / descriptive of the process. Lmk if you agree.

**Comment by adghayes** [comment]
@kofi-q can you take a look at this one?

**Comment by kofi-q** [comment]
Ah thanks, missed this - taking a look!

**Review by kofi-q — APPROVED** [review]
A+ commit organisation - thanks!

And +1 to standardising on "Manually Entered" or "Manually Added" - also leaning toward "Entered", but either seems fine as long as they're consistent

**Pull request merged**
