### PR TITLE
test(bmd): upgrade cypress

### PR DESCRIPTION
**Pull request by eventualbuddha**
## Overview
Also stops depending on the `/#demo` URL, which means we can remove `DemoApp` after this lands.

Refs #1615

## Demo Video or Screenshot

https://user-images.githubusercontent.com/1938/180103242-0bc79fa9-6a68-422c-b725-98c695bdea09.mov

## Testing Plan 
Automated testing.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Looks like [I need to make sure `smartcards` has all of its dependencies](https://app.circleci.com/pipelines/github/votingworks/vxsuite/4769/workflows/ef28e984-fd63-47fe-90f1-549cda06bab9/jobs/100889?invite=true#step-110-69) set up first. @carolinemodic, how do you feel about this being in `bmd` rather than in a new `integration-testing` folder? I'm not tied to this approach, it was just the easiest way to go.

**Comment by carolinemodic** [comment]
I think eventually we'll want to move over to the integration testing folder but it doesn't need to be tied to this PR. We still need to upgrade the cypress version in those tests too right?

**Comment by eventualbuddha** [comment]
Yeah, this doesn't touch those. But they should be pretty straightforward. Some of the changes in this PR were actually made by cypress.

**Comment by eventualbuddha** [comment]
This is ready to review if anyone wants to take a look. Automerge is on.

**Review by carolinemodic — APPROVED** [review]

**Pull request merged**
