### PR TITLE
VxAdmin desktop theme

### PR DESCRIPTION
**Pull request by jonahkagan**
## Overview

Task: #4236 
Closes: #2835 

Converts VxAdmin to use the desktop theme. The major changes are:
- Increasing the base font size to 24px based on what looks good on a Lenovo
- Reusing the sidebar nav and sticky header developed for VxDesign
- Reorganizing the write-in adjudication screen
- Restyling the report builders
- Restyling the manual data entry flow

_Review by commits_

## Demo Video or Screenshot
System Admin views
https://github.com/votingworks/vxsuite/assets/530106/7ae42902-f196-4972-9e80-87846b7c26df

Election Manager - Save ballot package
https://github.com/votingworks/vxsuite/assets/530106/e13ab315-4a36-4fa4-a974-7eba87fdcab7

Election Manager - Manual results
https://github.com/votingworks/vxsuite/assets/530106/b483b256-12c5-4fcd-aed9-2afe489053d0

Election Manager - Write-in adjudication
https://github.com/votingworks/vxsuite/assets/530106/224d643e-16f3-4999-a1b4-15a356d72d36

Election Manager - Reports
https://github.com/votingworks/vxsuite/assets/530106/5cfa0159-6b5b-40bf-bb51-571deb64d24c

## Testing Plan
- Manual testing
- Updated automated tests

## Checklist

- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.

- [ ] I have added a screenshot and/or video to this PR to demo the change
- [ ] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

**Comment by jonahkagan** [comment]
@adghayes Sending this your way for an initial review for the visual changes and the implementation while I work on updating the tests. I just want to get out ahead of any feedback you might have.

**Comment by adghayes** [comment]
@jonahkagan the test that is failing on CI is removed in another PR that's up for review, so I would just skip it or also remove it or something.

**Review by adghayes — APPROVED** [review]
@jonahkagan I think this looks fantastic and it makes me proud to have such polished looking products!

My only (minor) gripe is that the WIA flow is no longer easily navigable by keyboard. In making the official and write-in selection lists radio buttons, you now navigate through them with arrow keys, while navigating across sections or other buttons through tabbing. Also, the last focused radio button leaves an outline around it that is a little confusing, but is definitely visually distinct enough from a selected option. It's definitely not a blocker.

Everything else, and code, LGTM.

I left a separate note about the failing test.

**Comment by mattroe** [comment]
I haven't played with this to check any edge cases on real hardware, but overall LGTM from the videos. WIA and Tally Report Builder interfaces are SO much better.

**Comment by jonahkagan** [comment]
> My only (minor) gripe is that the WIA flow is no longer easily navigable by keyboard

Thanks for noting this. I was able to improve it a bit by fixing the focus logic. But yes, I agree that the way that you manipulate focus within radio groups is not as easy to use.

**Pull request merged**
