### PR TITLE
chore(all): Upgrade to Cypress 9

### LINKED ISSUE #1718: Update cypress to 9.* in `frontends/bmd`
#1445 uncovered that the current Cypress version used in `frontends/bmd` doesn't work in Node 16. We should upgrade Cypress in `frontends/bmd`, and potentially everywhere.

### PR DESCRIPTION
**Pull request by taravancil**
## Overview
Fixes #1718

## Demo Video or Screenshot
N/A

## Testing Plan 
Tests should pass.

## Checklist
- [x] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.
- [x] I have added JSDoc comments to any newly introduced exports

- [x] I have added a screenshot and/or video to this PR to demo the change
- [x] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

**Review by eventualbuddha — APPROVED** [review]
LGTM, assuming CI passes!

**Comment by taravancil** [comment]
> LGTM, assuming CI passes!

Boo, it did not. Will investigate in the morning!

**Comment by eventualbuddha** [comment]
Looks like the CI artifact paths need tweaking: https://github.com/votingworks/vxsuite/issues/1720.

**Comment by taravancil** [comment]
`queryBy...` [should not throw if an element is not found](https://testing-library.com/docs/queries/about#types-of-queries). I'm going to update `@testing-library/cypress` and see if that fixes the failing test.

**Comment by taravancil** [comment]
Darn, had a green run before rebasing to fix the conflicts in the lockfile. Investigating...

**Comment by eventualbuddha** [comment]
> Darn, had a green run before rebasing to fix the conflicts in the lockfile. Investigating...

Maybe it's a flaky test?

**Comment by taravancil** [comment]
@eventualbuddha it sure was! I'll file a ticket for the flaky test.

**Pull request merged**
