### PR TITLE
refactor(types): move `Optional` to `basics`

### PR DESCRIPTION
**Pull request by eventualbuddha**
## Overview

_(review by commit)_

Moves `Optional` to `@votingworks/basics`. Uses a codemod that can be used to move symbols generally.

## Demo Video or Screenshot
```sh
# update `Dictionary` references from `@votingworks/types` to `@votingworks/basics`
❯ ./bin/codemod-move-symbols --all Dictionary:types:basics
@votingworks/admin-backend: ✅ 1.27s (0 updated)
@votingworks/admin-frontend: src/components/ballot_counts_table.test.tsx: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/components/hand_marked_paper_ballot.tsx: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/config/globals.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/config/types.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/screens/manual_data_import_precinct_screen.tsx: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/screens/printed_ballots_report_screen.tsx: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/utils/election.test.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/utils/exportable_tallies.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/utils/external_tallies.test.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/utils/external_tallies.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/utils/write_ins.test.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: src/utils/write_ins.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: test/helpers/build_external_tally.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: test/util/build_candidate_tallies.tsx: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/admin-frontend: ✅ 1.68s (14 updated)
@votingworks/integration-testing-election-manager: cypress/support/assertions.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/integration-testing-election-manager: ✅ 1.06s (1 updated)
@votingworks/central-scan-backend: src/cvrs/build.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/central-scan-backend: ✅ 958.64ms (1 updated)
@votingworks/central-scan-frontend: ✅ 979.29ms (0 updated)
@votingworks/central-scan-integration-testing: ✅ 700.99ms (0 updated)
@votingworks/mark-backend: ✅ 654.48ms (0 updated)
@votingworks/mark-frontend: src/app_polls_flows.test.tsx: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/mark-frontend: ✅ 1.16s (1 updated)
@votingworks/mark-integration-testing: ✅ 303.26ms (0 updated)
@votingworks/scan-backend: src/cvrs/build.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/scan-backend: ✅ 922.73ms (1 updated)
@votingworks/scan-frontend: src/app_tally_report_paths.test.tsx: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/scan-frontend: src/screens/poll_worker_screen.tsx: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/scan-frontend: ✅ 926.29ms (2 updated)
@votingworks/codemods: ✅ 594.68ms (0 updated)
@votingworks/api: ✅ 508.01ms (0 updated)
@votingworks/auth: ✅ 893.3ms (0 updated)
@votingworks/backend: ✅ 727.17ms (0 updated)
@votingworks/ballot-encoder: ✅ 541.24ms (0 updated)
@votingworks/ballot-interpreter-nh: ✅ 731.28ms (0 updated)
@votingworks/ballot-interpreter-nh-next: ✅ 497.75ms (0 updated)
@votingworks/ballot-interpreter-vx: ✅ 647.38ms (0 updated)
@votingworks/basics: ✅ 322.31ms (0 updated)
@votingworks/cdf-schema-builder: ✅ 346.11ms (0 updated)
@votingworks/custom-scanner: ✅ 755.62ms (0 updated)
@votingworks/cvr-fixture-generator: ✅ 743.79ms (0 updated)
@votingworks/db: ✅ 248.91ms (0 updated)
@votingworks/fixtures: ✅ 935.76ms (0 updated)
@votingworks/grout: ✅ 330.51ms (0 updated)
@votingworks/grout-test-utils: ✅ 580.45ms (0 updated)
@votingworks/image-utils: ✅ 488.8ms (0 updated)
@votingworks/logging: src/logger.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/logging: src/types.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/logging: ✅ 604.51ms (2 updated)
@votingworks/message-coder: ✅ 402.45ms (0 updated)
@votingworks/plustek-scanner: ✅ 635.34ms (0 updated)
@votingworks/res-to-ts: ✅ 510.1ms (0 updated)
@votingworks/test-utils: src/cast_vote_record.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/test-utils: ✅ 537.25ms (1 updated)
@votingworks/types: ✅ 476.36ms (0 updated)
@votingworks/ui: src/tally_report_summary.tsx: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/ui: ✅ 1.14s (1 updated)
@votingworks/utils: src/compressed_tallies.test.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/utils: src/compressed_tallies.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/utils: src/tallies.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/utils: src/types.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/utils: src/votecounting.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/utils: src/votes.ts: Dictionary: @votingworks/types → @votingworks/basics
@votingworks/utils: ✅ 713.5ms (6 updated)
```

## Testing Plan
Automated.

## Checklist

- [ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.
- [ ] I have added JSDoc comments to any newly introduced exports

- [ ] I have added a screenshot and/or video to this PR to demo the change
- [ ] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

**Review by adghayes — COMMENTED** [review]
@eventualbuddha didn't you have a recursive way to run this on all libraries except a few? Can you add that to the comment if so? I know you will get questions about it. Approved, but auto-merge is on so will wait to click the button.

**Comment by adghayes** [comment]
Following the instructions in the PR description, I get the following error:

```
bash: bin/codemod-move-symbols: No such file or directory
```

I think it should actually be run from `codemods`? But if I run it from `codemods` I get:

```
bin/codemod-move-symbols: line 9: /home/drew/code/vxsuite/codemods/bin/../node_modules/.bin/tsx: No such file or directory
```

**Comment by eventualbuddha** [comment]
@adghayes should be fixed now.

**Review by adghayes — APPROVED** [review]
I'm very excited to have this utility at my disposal! I suggest you make a post to #vxsuite-prodeng because I'm sure people will appreciate this.

After testing it out, I think it would be ideal if, with the `--all` option, you could (or it would just automatically) exclude the source and target packages as they probably require special handling. Up to you.

**Comment by eventualbuddha** [comment]
> I'm very excited to have this utility at my disposal! I suggest you make a post to #vxsuite-prodeng because I'm sure people will appreciate this.

Will do.

> After testing it out, I think it would be ideal if, with the `--all` option, you could (or it would just automatically) exclude the source and target packages as they probably require special handling. Up to you.

Good suggestion, I added it in 7d97de7.

**Pull request merged**
