### PR TITLE
[Scan] Left-align ballot count when there's no header title

### PR DESCRIPTION
**Pull request by kofi-q**
## Overview

Closes https://github.com/votingworks/vxsuite/issues/4964

Removing the title placeholder in the screen header when there's no title, so that the scanned ballot count falls to the left in those cases.

## Demo Video or Screenshot
| Single-Language  | Multi-Language |
| ------------- | ------------- |
| Screenshot 2024-08-22 at 12 34 29 | Screenshot 2024-08-22 at 12 34 08 |
| Screenshot 2024-08-22 at 12 34 38 | Screenshot 2024-08-22 at 12 34 45 |

## Testing Plan
- Manual

## Checklist

- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.~

- [x] I have added a screenshot and/or video to this PR to demo the change
- [x] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

**Comment by arsalansufi** [comment]
cc @mattroe (who I know has had opinions on this for a while hah and might've been preferring a full-width button in this case)

**Comment by kofi-q** [comment]
> cc @mattroe (who I know has had opinions on this for a while hah and might've been preferring a full-width button in this case)

Ah, that could work too - @mattroe, LMK if either of these is what you're thinking:

### Full-size settings, leaving ballot count right-aligned:
Screenshot 2024-08-20 at 17 07 50

### Full-size settings, changing ballot count to left-aligned when there's no screen title:
Screenshot 2024-08-20 at 17 08 26

**Comment by mattroe** [comment]
My vote is full-width button right-aligned. I think it's valuable to *not* change the count location depending on state for poll workers. The whitespace also feels a bit weird to me keeping the same button width, but that may just be because I'm used to the space being utilized at this point.

**Comment by carolinemodic** [comment]
@kofi-q I agree with keeping it right aligned too fwiw, should I wait to review this?

**Comment by kofi-q** [comment]
> My vote is full-width button right-aligned.

Perfect - that's where I was leaning too. Glad we get to keep the right alignment consistent

**Comment by kofi-q** [comment]
K, @carolinemodic, updated the code and screenshots - ready for review ✅

**Comment by jonahkagan** [comment]
Would it be possible to have a regular width button on the left and the count on the right in the same row? I feel like the full width button is so long that it doesn't necessarily read as a button anymore.

**Comment by mattroe** [comment]
> Would it be possible to have a regular width button on the left and the count on the right in the same row? I feel like the full width button is so long that it doesn't necessarily read as a button anymore.

That would be my preference - I just assumed it was a challenge to implement considering we didn't start there, but maybe bad assumption.

**Review by carolinemodic — APPROVED** [review]

**Comment by kofi-q** [comment]
Ahh, gotcha - will iterate on that

**Comment by kofi-q** [comment]
@carolinemodic - sorry for the thrash! Few more changes after slack design iteration - ready for one last sanity check

**Review by carolinemodic — APPROVED** [review]
no problem!

**Pull request merged**
