### PR TITLE
Migrate `bsd` and `election-manager` to `apps` structure

### LINKED ISSUE #2287: Rename frontends/election-manager frontends/admin to avoid confusion with election manager user role
Rename frontends/election-manager frontends/admin (or something along those lines) to avoid confusion with election manager user role

### LINKED ISSUE #2976: Move VxCentralScan and VxAdmin into new /apps directory structure
This will also involve updating vxsuite-complete-system build scripts

### PR DESCRIPTION
**Pull request by adghayes**
## Overview
Closes #2976. Moves `bsd` to `apps/central-scan` and `election-manager` to `apps/admin`. With this change, all four of our apps are in the `apps` structure. 

In moving the apps, this changes:
- `frontends/bsd` > `apps/central-scan/frontend`
- `services/scan` > `apps/central-scan/backend`
- `frontends/election-manager` > `apps/admin/frontend`
- `services/admin` > `apps/admin/backend`

The PR also takes advantage of the change to colocate the integration testing with the apps (awesome improvement @carolinemodic!):
- `integration-testing/bsd` > `apps/central-scan/integration-testing`
- `integration-testing/election-manager` > `apps/admin/integration-testing`

As I'm writing this, I realize that I need to make an additional commit to move the shared `integration-testing/README.md` into the split libraries. 

I tried to remove references to `election-manager` and `bsd` except in outdated comments, so this should close #2287.

Also, as a follow-up PR, we could structure the VxMark integration testing in a similar way for consistency.

### CODE REVIEW

**Comment by adghayes** [comment]
@carolinemodic I'll swap this to ready for review once I update description, but you'll just have to update the branch protection again 🙃.

**Comment by adghayes** [comment]
@carolinemodic I will take a look at `vxsuite-complete-system` and make a PR there.

**Comment by carolinemodic** [comment]
Yeah I was thinking we should update VxMark's integration testing as a followup PR as well

**Comment by arsalansufi** [comment]
My merge of https://github.com/votingworks/vxsuite/pull/2999 just created a few merge conflicts here - let me know if I can help with them! I'm hopeful they won't be too bad 🤞

**Review by arsalansufi — APPROVED** [review]
Thanks for taking this on Caro and Drew!

**Pull request merged**
