### PR TITLE
feat(bsd): clarify adjudication screen

### LINKED ISSUE #443: VxCentralScan: adjudication screen should be clarified
Right now, our screen tries to be aligned with the Ms process, but because that process isn't consistent, it's not helpful. Instead, we should have the text describe the exact action that the *scanner* is taking, not the ones that the adjudication board will take. Specifically, using the term "duplicate ballot" is confusing.

So, the text should read:

----

## Overvote

The last ballot was not tabulated.

[Send to resolution board]

or

[Tabulate as is]

----

Instead of an upper-right-hand corner confirmation, clicking either button should pop up a modal.

In the case of send to resolution board, the modal should read:

----

You have chosen to send this ballot to the resolution board.

Please remove this ballot from the stack.

[Cancel] [I've removed the ballot]

----

In the case of "Tabulate as Is":

----

You have chosen to tabulate this ballot as is.

[Cancel] [Tabulate as is]

----

### PR DESCRIPTION
**Pull request by beausmith**
## Overview
Closes #443

## Demo Video or Screenshot
image
image
image

### CODE REVIEW

**Comment by benadida** [comment]
One of the changes I'd made was to remove the explicit mention of a resolution board, because it varies from state to state in name and process. Plus, are we actually sending to resolution board in our product? I suggest sticking to "remove ballot from count" or something like that.

Otherwise looks great.

**Review by benadida — APPROVED** [review]
I have a slight preference for not using terminology like "resolution board" which differs from state to state and which assumes more than needed. But, I can live with it.

**Comment by mattroe** [comment]
Agree with @benadida on the desire to generalize terminology when we can. 

`Remove to Adjudicate`?
`Remove to Review`?

**Comment by beausmith** [comment]
Agree on generic language. "Resolution Board" was in the issue copy the @benadida wrote, so I assumed this was what was wanted. Happy to update this to @mattroe's suggestion "Remove to Adjudicate"

**Comment by benadida** [comment]
> Agree on generic language. "Resolution Board" was in the issue copy the @benadida wrote, so I assumed this was what was wanted. Happy to update this to @mattroe's suggestion "Remove to Adjudicate"

HAH HAH, I am hoisted on my own petard! ;)

OK, cool, glad we agree, sorry for the misdirection.

**Pull request merged**
