### PR TITLE
feat: include ballot type in the CVR output

### LINKED ISSUE #41: module-scan: make sure every CVR includes all mode bits
absentee, test, etc.

### PR DESCRIPTION
**Pull request by eventualbuddha**
Closes #41

Looking for design feedback here, @benadida. Name of the `_ballotType`, values, etc.

### CODE REVIEW

**Review by carolinemodic — APPROVED** [review]
I don't really have any thoughts on the naming of the different ballot types but the code looks good to me.

**Review by benadida — COMMENTED** [review]
I'm wondering if `provisional` will ever be an actual ballot type on the ballot itself, or if it's a normal ballot wrapped in a provisional envelope, and when it gets counted it becomes a standard ballot.

Worth some input from @ginvdr and @mcchilders to understand the exact provisional flow and reporting needs.

**Comment by eventualbuddha** [comment]
Alright, I'm going to merge this and we can revisit if @mcchilders or @ginvdr think it needs changes.

**Comment by ginvdr** [comment]
Some states might want something like that but I'd be cautious - If an election has a low provisional ballot rate, they could be compromising voter anonymity.

**Pull request merged**
