### PR TITLE
feat(scan): CLI for PDI scanner

### PR DESCRIPTION
**Pull request by eventualbuddha**
## Overview
Requires getting the kernel module and `libPDIScan` shared library set up properly first. Needs a decent amount of cleanup and testing before we can merge this.

To try it out, `cd libs/pdi-rs && cargo run --release`. More comprehensive instructions [here](https://docs.google.com/document/d/1zKlPy0SxL3P1AbZs9TfP5L_1PJ4m0u60RR9-uW5n_14/edit).

## Demo Video or Screenshot
image

Demo video where I start an auto-scan session and scan a single document:

https://github.com/votingworks/vxsuite/assets/1938/f187052c-6f5e-4246-8736-7b5e8b39c4ad

## Testing Plan
- [ ] Manual
- [ ] Automated

### CODE REVIEW

**Comment by benadida** [comment]
@eventualbuddha I've been slacking here. Is a review still useful?

**Comment by eventualbuddha** [comment]
Reviewing the TUI from a user perspective would be potentially useful, otherwise you can just let @kshen0 review when the VxScan integration is done.

**Review by benadida — APPROVED** [review]
just from a TUI user perspective, as per @eventualbuddha 's request – I love having this and it looks powerful enough to test all the thing. 👍

**Comment by arsalansufi** [comment]
Closing this out as we now have a proper integration and this CLI is now out of sync with main

**Pull request closed without merging**
