### PR TITLE
[i18n/Audio] <UiString>-ify the MsEitherNeitherContest in mark-flow-ui

### PR DESCRIPTION
**Pull request by kofi-q**
## Overview

Converting text in the `MsEitherNeitherContest` screen (used in `Mark`/`Mark-Scan`) to language-aware `<UiString>`s.

## Demo Video or Screenshot
| Default | Sample Translation |
| ------------- | ------------- |
| Screenshot 2023-11-09 at 11 39 51 | Screenshot 2023-11-09 at 11 39 00 |
| Screenshot 2023-11-09 at 11 39 54 | Screenshot 2023-11-09 at 11 39 04 |
| Screenshot 2023-11-09 at 11 39 58 | Screenshot 2023-11-09 at 11 39 19 |
| Screenshot 2023-11-09 at 11 40 01 | Screenshot 2023-11-09 at 11 39 13 |
| Screenshot 2023-11-09 at 11 40 04 | Screenshot 2023-11-09 at 11 39 19 |

## Testing Plan
- Manual verification + existing tests as regression check

## Checklist

- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.~

- [x] I have added a screenshot and/or video to this PR to demo the change
- [x] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates

### CODE REVIEW

**Review by arsalansufi — APPROVED** [review]
Change looks good! I think you'll want to rebase onto the latest main so that the (now committed) catalog is properly updated (a la https://github.com/votingworks/vxsuite/pull/4188). Otherwise, the CI build will fail when you merge to main

**Comment by kofi-q** [comment]
> Otherwise, the CI build will fail when you merge to main

Oh yeah, thanks for the heads-up!

**Comment by arsalansufi** [comment]
Actually just realized that you may have to rebase again because of https://github.com/votingworks/vxsuite/pull/4194 hah

**Comment by kofi-q** [comment]
> Actually just realized that you may have to rebase again because of https://github.com/votingworks/vxsuite/pull/4194 hah

I was just wondering about that 😅

**Pull request merged**
