### PR TITLE
feat(em): Consistent Capitalization for Ballot Instruction Headings

### LINKED ISSUE #2410: Update Ballot Instruction Titles to Title Case
Inconsistent capitalization in the ballot instruction section headlines: “To Vote for a Write-In” vs “To correct a mistake”

Smallest change:
- “To correct a mistake” ➡️  “To Correct a Mistake”

Ideal Change:
- **Instructions**
- **To Add a Candidate** (Simpler language. This was used in a Choctaw County election.)
- **To Correct a Mistake**

⚠️ Warning ⚠️
This phrase is a key for optional translation strings. This change will cause some past election configurations with optional language string to no longer work. 

Issue automatically created from slack feedback reported by @jonahkagan: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1660757414282199?thread_ts=1660757414.282199&cid=CJU9MSC6S

### PR DESCRIPTION
**Pull request by beausmith**
Fixes #2410

### CODE REVIEW

**Comment by eventualbuddha** [comment]
You're gonna need to do some updating of hashes and renaming of files/folders. Maybe the folders that have a partial hash in the name should not have that hash anymore to make this sort of change less annoying.

**Review by benadida — APPROVED** [review]

**Comment by benadida** [comment]
@beausmith Hmm, I just approved this, but now I'm having second thoughts: have you had a chance to think through the impact on this on existing election definitions?

**Comment by beausmith** [comment]
I paused because discussion is needed to discuss tradeoffs in order to proceed. There are a couple past Slack threads with some discussion.

**Comment by carolinemodic** [comment]
Closing since this isn't active @beausmith feel free to reopen if we want to merge this.

**Pull request closed without merging**
