### PR TITLE
Fix occasional test deck misordering

### PR DESCRIPTION
**Pull request by arsalansufi**
# Overview

Issue link: https://github.com/votingworks/vxsuite/issues/1868

This was a super interesting one. Drew and I were occasionally seeing misordered test decks get generated on our laptops, e.g. ballot styles were interleaved, the first HMPB in the test deck had bubbles other than the first in each contest filled in, etc.

After some investigation, we pinpointed this to an issue with our Paged.js-processing of HMPBs. While the ballots are [originally rendered in the correct order](https://github.com/votingworks/vxsuite/blob/3e1689bdb1db2e7bf9c4e874ab74662d78fd9275/frontends/election-manager/src/screens/print_test_deck_screen.tsx#L144-L157), there's no guarantee that the initial order will be maintained as [each is processed by Paged.js](https://github.com/votingworks/vxsuite/blob/3e1689bdb1db2e7bf9c4e874ab74662d78fd9275/frontends/election-manager/src/components/hand_marked_paper_ballot.tsx#L623-L627). Every ballot processes itself, unaware of the other ballots, and renders its processed self to a shared target element ([the element referenced by `printBallotRef`](https://github.com/votingworks/vxsuite/blob/3e1689bdb1db2e7bf9c4e874ab74662d78fd9275/frontends/election-manager/src/components/hand_marked_paper_ballot.tsx#L626)).

In the screenshot below, for example, you can see that what was originally ballot 22 is the first ballot among the processed ballots.

pagedjs

To fix this, we now render every processed ballot to a unique target element instead of a shared one. These target elements are created and cleared on the fly as needed.

Below is a (surprisingly relaxing 😌) video demonstrating this in action. Note how processing begins with ballot 22 and loops back to ballot 0 - before this fix, this would've resulted in a misordered test deck!

https://user-images.githubusercontent.com/12616928/170114229-e7e25d1c-8705-4654-8622-c472d623d347.mov

# Testing

- [x] Verified that automated tests still pass (with small expected tweaks to snapshots/mocks)
- [x] Manually tested the single-precinct case
- [x] Manually tested the all-precincts case
- [x] Verified that target elements were created _and cleared_ on the fly, via Chrome dev tools

# Checklist

- [ ] ~I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced~ N/A
- [ ] ~I have added JSDoc comments to any newly introduced exports~ N/A
- [x] I have added a screenshot and/or video to this PR to demo the change
- [ ] ~I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates~ N/A

### CODE REVIEW

**Comment by adghayes** [comment]
@arsalansufi what's the reason for / advantage of the current implementation instead of just wrapping each `HandMarkedPaperBallot` in a `div` here? https://github.com/votingworks/vxsuite/blob/4e047d6a90d56b0befb10b6d901e121965c8f489/frontends/election-manager/src/screens/print_test_deck_screen.tsx#L157-L161

**Review by benadida — APPROVED** [review]
I don't have an issue with this implementation, though I would +1 @adghayes 's question: is there a much simpler way to do this by just adding a `<div>` in the markup itself?

Approve to give you flexibility to merge since I don't see a problem with this implementation, but nudge to consider the simpler solution if it does, in fact, work.

**Comment by arsalansufi** [comment]
Excellent question @adghayes and @benadida! I should've left some notes proactively about why I ultimately didn't take that approach, since you're absolutely right that it's the intuitive approach.

I tried a few different permutations of divs rendered through React either in `HandMarkedPaperBallot` or one-level higher in `HandMarkedPaperBallots` (plural) but couldn't get them to work.

For example, when I tried wrapping `HandMarkedPaperBallot` in a new div and rendering to that, the resulting ballots were styled incorrectly.

improperly-rendered-ballot

I didn't get to an exact root cause, but my sense was that the React render lifecycle was interrupting Paged.js processing.

When I moved the divs up one-level to `HandMarkedPaperBallots` (plural), same issue.

I ultimately concluded that the divs needed to be rendered 1) separate from `HandMarkedPaperBallot` and 2) in advance of `HandMarkedPaperBallot`. To meet these criteria , I rendered the divs within the isolated div that HMPBs are currently rendered to (`printBallotRef`). And I did so in a way that guarantees that the divs exist before `HandMarkedPaperBallot` tries rendering to them.

All this said, I could perhaps still meet these criteria while also rendering through React instead of JS. Let me do a final timeboxed exploration to see if I can strike a happy medium! I'll also add a brief comment noting the constraints I've encountered.

**Comment by benadida** [comment]
> Excellent question @adghayes and @benadida! I should've left some notes proactively about why I ultimately didn't take that approach, since you're absolutely right that it's the intuitive approach.

I'm convinced! My goal is simplicity, and if this is the simplest thing that *works* now, let's do it and move forward.

**Pull request merged**
